### ISSUE TITLE
On the Projects page - all projects should spell out their full names

### ISSUE THREAD

**Issue by jakob-engblom-i** [accellera-official/systemc.org#10]
Now we have "SCC" and "VCML" etc. without writing out what they mean.  Which makes it hard to know if the SCC listed here is the same as some other SCC...   This should be added to some kind of policy doc.  Not sure that it is appropriate for me to patch the contents to do this.

**Comment by barnasc** [comment]
solved in https://github.com/accellera-official/systemc.org/pull/13
