### ISSUE TITLE
Vivado HLS has no longer support for SystemC design entry

### ISSUE THREAD

**Issue by rlmarco** [accellera-official/systemc.org#24]
Sadly, it seems Vivado HLS doesn't support SystemC for design entry any more: [https://support.xilinx.com/s/article/73613?language=en_US](url). Perhaps it is necessary to update Tools page in systems.org

**Comment by barnasc** [comment]
Thanks for reporting. Tool removed from list in https://github.com/accellera-official/systemc.org/commit/ec40bec546f3c39547e5b9fad37f0eea60afa6f9
