### ISSUE TITLE
SystemC education is missing CUAS

### ISSUE THREAD

**Issue by wscherr-cuas** [accellera-official/systemc.org#31]
Please add following entry to the education list:

University: Carinthia University of Applied Sciences
Link: https://www.fh-kaernten.at/iscd

Country: Austria

Department: Integrated Systems and Circuit Design (ISCD)

Lecture:  System Modelling and Verification - Analog
Lecture:  System Modelling and Verification - Digital
Lecture:  System-on-Chip Architectures

(see also curriculum description on web site)

Thanks!
Wolfgang

**Comment by barnasc** [comment]
implemented in https://github.com/accellera-official/systemc.org/commit/01b7ed86587ce8c9dd279a6bd539b57cdd2f359a

**Comment by wscherr-cuas** [comment]
Thanks for adding! It seems there is a slight issue with the referred URL index in the table, it should point to 15 (CUAS) and not 14 (Genoble). Thanks again!
