### ISSUE TITLE
Wrong link for CUAS in the education table.

### ISSUE THREAD

**Issue by wscherr-cuas** [accellera-official/systemc.org#32]
Thanks for adding CUAS. It seems there is a slight issue with the referred URL index in the table, it should point to entry #15 and not #14. Thanks again!

**Comment by wscherr-cuas** [comment]
I created already a pull request with the fix using the Web portal.

**Comment by barnasc** [comment]
solved in https://github.com/accellera-official/systemc.org/pull/34
