### ISSUE TITLE
Missing Tool

### ISSUE THREAD

**Issue by onkar1410** [accellera-official/systemc.org#36]
Agnisys's IDesignSpec also supports SystemC

**Comment by barnasc** [comment]
please share a link to your company website and product

**Comment by onkar1410** [comment]
Hi,

Here's the link to Agnisy's website:
https://www.agnisys.com/
Product page:
https://www.agnisys.com/products

Thank you,
Onkar Mishra
Marketing Executive
Agnisys Inc.

**Comment by barnasc** [comment]
The page/product shared in these links do not state explicitly that it supports SystemC.
