### ISSUE TITLE
Add CSU program to eductaion table

### ISSUE THREAD

**Issue by EPIC-CSU** [accellera-official/systemc.org#40]
Please add the following course that has been teaching systemc for the past 12 years: 

University: Colorado State University ((https://www.engr.colostate.edu/~sudeep/teaching/hardwaresoftware-design-of-embedded-systems/)
Department: Embedded, High Performance, and Intelligent Computing (EPIC)
Country: USA
Course/Lectures: Hardware/Software Design of Embedded Systems

**Comment by barnasc** [comment]
Thank you to report this issue and suggestion to improve systemc.org. It has been implemented.
