### ISSUE TITLE
Add SingleSource communication channels library

### ISSUE THREAD

**Issue by mikhailmoiseev** [accellera-official/systemc.org#42]
Please add SingleSource communication channels  described [here](https://github.com/intel/systemc-compiler/wiki/SingleSource-library).
The the channels available at Apache 2.0 license, code given at https://github.com/intel/systemc-compiler/tree/main/components/common/sctcommon

The SingleSource library consists of communication channels which implements functional interfaces similar to TLM 1.0. The channels support cycle accurate mode for simulation and synthesis (the implementation complies to SystemC synthesizable standard). The channels also have fast simulation mode to be used in architecture exploration, performance evaluation and virtual protyping. 

There are multiple examples of channels usage given [here](https://github.com/intel/systemc-compiler/tree/main/designs/single_source)

**Comment by barnasc** [comment]
Thank you to report this issue and suggestion to improve systemc.org. It has been implemented.
