### ISSUE TITLE
Add SystemC TLM based Virtual Prototype: RISC-V VP++ from Institute for Complex Systems JKU Linz

### ISSUE THREAD

**Issue by mschlaegl** [accellera-official/systemc.org#46]
Hello,

please add our project RISC-V VP++ to https://systemc.org/resources/projects/

RISC-V VP++ is an open-source, RISC-V virtual prototype based on SystemC TLM.
It is capable of running bare-metal software, real-time operating systems and even Linux systems with interactive graphical applications that are network-capable.

Link: https://github.com/ics-jku/riscv-vp-plusplus

In addition, there is the GUI-VP_Kit, which aims to provide a quick-to-create and easy-to-use platform for experimenting with Linux on the RISCV-VP++.

Link: https://github.com/ics-jku/GUI-VP_Kit

Thank you in advance!

**Comment by barnasc** [comment]
implemented in #46. Note that the GUI-VP_Kit lib on GitHub does not explicitly lists the license.
