### ISSUE TITLE
Politecnico di Torino

### ISSUE THREAD

**Issue by saravinco** [accellera-official/systemc.org#47]
At Politecnico di Torino we are performing research on SystemC AMS, to build virtual prototypes and support the modeling of extra-functional properties such as power. The main contact person on the topic is Prof. Sara Vinco: [https://www.polito.it/en/staff?p=032283](url)

Politecnico main web page: [https://www.polito.it/](url)

Relevant projects: 
- MESSY: Multi-layer Extra-functional Simulator in SYstemc, https://github.com/eml-eda/messy

Relevant publications: 

- A novel virtual prototyping methodology for timing-accurate simulation of AMS circuits, https://ieeexplore.ieee.org/document/10528712
- Integrating SystemC-AMS power modeling with a RISC-V ISS for virtual prototyping of battery-operated embedded devices, https://arxiv.org/abs/2404.01861
- Modeling Cyber-Physical Production Systems with SystemC-AMS, https://ieeexplore.ieee.org/document/9969885
- Modeling and Simulation of Cyber-Physical Electrical Energy Systems with SystemC-AMS, https://ieeexplore.ieee.org/document/8999635
- A SystemC-AMS Framework for the Design and Simulation of Energy Management in Electric Vehicles, https://ieeexplore.ieee.org/document/8648435
- SystemC-AMS thermal modeling for the co-simulation of functional and extra-functional properties, https://dl.acm.org/doi/10.1145/3267125
- SystemC-AMS Simulation of Energy Management of Electric Vehicles, https://ieeexplore.ieee.org/document/8612387
- A Layered Methodology for the Simulation of Extra-Functional Properties in Smart Systems, https://ieeexplore.ieee.org/document/7812663

**Comment by barnasc** [comment]
thanks for sharing this initiative and publications. I've updated the projects and publications page accordingly.

Note that we only list open access publications at systemc.org. This means from your list we only reference to the paper listed at arxiv.org. If any of the other papers is published as open/free access, please let us know and we will add the link.
