### ISSUE TITLE
SystemC & TLM2.0 courses to add to https://systemc.org/resources/training/ page

### ISSUE THREAD

**Issue by SamBascal** [accellera-official/systemc.org#48]
Hello
Thank for helping to promote Doulos training courses. It's much appreciated.

Can you please add the following to the Doulos live training list on https://systemc.org/resources/training/  :
[Comprehensive C++ Online](https://www.doulos.com/training/soc-design-and-verification/systemc-tlm-20/comprehensive-cplusplus-online/)

And the following SystemC & TLM-2.0 **Self-Paced** training:
•	[Essential C++ for SystemC Self-Paced](https://www.doulos.com/training/soc-design-and-verification/systemc-tlm-20/essential-cplusplus-for-systemc-self-paced/) 
•	[Fundamentals of SystemC Self-Paced](https://www.doulos.com/training/soc-design-and-verification/systemc-tlm-20/fundamentals-of-systemc-self-paced/) 
•	[SystemC Modeling using TLM-2.0 Self-Paced](https://www.doulos.com/training/soc-design-and-verification/systemc-tlm-20/systemc-modeling-using-tlm-20-self-paced/) 
•	[Comprehensive SystemC Self-Paced Bundle](https://www.doulos.com/training/soc-design-and-verification/systemc-tlm-20/comprehensive-systemc-self-paced-bundle/) 
•	[Comprehensive SystemC and TLM-2.0 Modeling Self-Paced Bundle](https://www.doulos.com/training/soc-design-and-verification/systemc-tlm-20/comprehensive-systemc-and-tlm-20-modeling-self-paced-bundle/)

Best regards
Sam Bascal 
VP of Engineering at Doulos

**Comment by barnasc** [comment]
Thanks for sharing the updated training list.
Training page has been updated.
